export const testExample = [
  {
    id: 0,
    title: "Question 1: What is right?",
    comment: "Right answer is at the moon",
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    selected: true,
    files: [],
    previews: [],
    answerOptions: [
      { id: 0, text: "left", isCorrect: false },
      { id: 1, text: "right", isCorrect: false },
      {
        id: 2,
        text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
        isCorrect: true,
      },
    ],
  },
  {
    id: 1,
    title: "Question 2: How are you today?",
    comment: "",
    maxPoints: 3,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    type: 2,
    selected: false,
    answerOptions: [{ id: 0, text: "Great!" }],
  },
  {
    id: 2,
    title: "Question 3: Lorem ipsum dolor?",
    comment: "",
    maxPoints: 3,
    type: 1,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "lorem", isCorrect: true },
      { id: 1, text: "ipsum", isCorrect: true },
      { id: 2, text: "dolor", isCorrect: false },
    ],
  },
  {
    id: 3,
    title: "Question 4: Lorem ipsum dolor?",
    comment: "Provide explanation on lorem ipsum",
    maxPoints: 3,
    type: 2,
    selected: false,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    answerOptions: [
      {
        id: 0,
        text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
      },
    ],
  },
  {
    id: 4,
    title: "Question 5: What is right?",
    comment: "Right answer is at the moon",
    points: 1,
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "left", isCorrect: false },
      { id: 1, text: "right", isCorrect: true },
      { id: 2, text: "wrong", isCorrect: false },
    ],
  },
  {
    id: 5,
    title: "Question 6: What is right?",
    comment: "Right answer is at the moon",
    points: 0,
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "left", isCorrect: false },
      { id: 1, text: "right", isCorrect: false },
      { id: 2, text: "wrong", isCorrect: true },
    ],
  },
  {
    id: 6,
    title: "Question 7: What is right?",
    comment: "Right answer is at the moon",
    points: 0,
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "left", isCorrect: false },
      { id: 1, text: "right", isCorrect: false },
      { id: 2, text: "wrong", isCorrect: true },
    ],
  },
];

export const answersGrid = [
  {
    student: {
      email: "m.kind@vdu.lt",
      name: "Mary the Student",
      customId: "IF200001",
    },
    startEnd: {
      start: "December 14, 10:00",
      end: "December 14, 11:00",
    },
    grade: null,
    status: 1,
    isShown: true,
  },
  {
    student: {
      email: "po456@example.com",
      name: "Paula Ortiz",
      customId: "PO00456",
    },
    startEnd: {
      start: "December 14, 10:30",
      end: "December 14, 11:30",
    },
    grade: {
      grade: 9,
      percent: 92,
    },
    status: 3,
    isShown: true,
  },
  {
    student: {
      email: "if789@example.com",
      name: "Isaac Freeman",
      customId: "IF00789",
    },
    startEnd: {
      start: "December 14, 11:00",
      end: "December 14, 12:00",
    },
    grade: null,
    status: 1,
    isShown: true,
  },
  {
    student: {
      email: "po101@example.com",
      name: "Pia Olsen",
      customId: "PO00101",
    },
    startEnd: {
      start: "December 14, 11:30",
      end: "December 14, 12:30",
    },
    grade: null,
    status: 1,
    isShown: true,
  },
  {
    student: {
      email: "if112@example.com",
      name: "Irene Fisher",
      customId: "IF00112",
    },
    startEnd: {
      start: "December 15, 12:00",
      end: "December 15, 13:00",
    },
    grade: {
      grade: 6,
      percent: 57.55,
    },
    status: 3,
    isShown: true,
  },
  {
    student: {
      email: "po123@example.com",
      name: "Pedro Ochoa",
      customId: "PO00123",
    },
    startEnd: {
      start: "December 15, 12:30",
      end: "December 15, 13:30",
    },
    grade: {
      grade: 5,
      percent: 52.01,
    },
    status: 3,
    isShown: true,
  },
  {
    student: {
      email: "if134@example.com",
      name: "Ivy Foster",
      customId: "IF00134",
    },
    startEnd: {
      start: "December 15, 13:00",
      end: "December 15, 14:00",
    },
    grade: {
      grade: 4,
      percent: 44.29,
    },
    status: 4,
    isShown: false,
  },
  {
    student: {
      email: "po145@example.com",
      name: "Pablo Ortega",
      customId: "PO00145",
    },
    startEnd: {
      start: "December 16, 13:30",
      end: "December 16, 14:30",
    },
    grade: {
      grade: 3,
      percent: 28.12,
    },
    status: 4,
    isShown: false,
  },
  {
    student: {
      email: "if156@example.com",
      name: "Ingrid Frank",
      customId: "IF00156",
    },
    startEnd: {
      start: "December 17, 14:00",
      end: "December 17, 14:25",
    },
    grade: null,
    status: 1,
    isShown: false,
  },
  {
    student: {
      email: "po167@example.com",
      name: "Peter O'Brien",
      customId: "PO00167",
    },
    startEnd: {
      start: "December 17, 14:00",
      end: "December 17, 14:00",
    },
    grade: null,
    status: 1,
    isShown: false,
  },
];
