export const testExample = [{
    id: 0,
    title: "Question 1: What is right?",
    comment: "Right answer is at the moon",
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
      aiCheck: true,
      plagiarismCheck: true,
      allowFiles: false,
      selected: true,
      files: [],
      previews: [],
      answerOptions: [
      { id: 0, text: "left", isRight: false },
      { id: 1, text: "right", isRight: false },
      {
        id: 2,
        text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
        isRight: true,
      },
    ],
  },
  {
    id: 1,
    title: "Question 2: How are you today?",
    comment: "",
    maxPoints: 3,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    type: 2,
    selected: false,
    answerOptions: [{ id: 0, text: "Great!" }],
  },
  {
    id: 2,
    title: "Question 3: Lorem ipsum dolor?",
    comment: "",
    maxPoints: 3,
    type: 1,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "lorem", isRight: true },
      { id: 1, text: "ipsum", isRight: true},
      { id: 2, text: "dolor", isRight: false },
    ],
  },
  {
    id: 3,
    title: "Question 4: Lorem ipsum dolor?",
    comment: "Provide explanation on lorem ipsum",
    maxPoints: 3,
    type: 2,
    selected: false,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    answerOptions: [
      {
        id: 0,
        text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
      },
    ],
  },
  {
    id: 4,
    title: "Question 5: What is right?",
    comment: "Right answer is at the moon",
    points: 1,
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "left", isRight: false },
      { id: 1, text: "right", isRight: true },
      { id: 2, text: "wrong", isRight: false },
    ],
  },
  {
    id: 5,
    title: "Question 6: What is right?",
    comment: "Right answer is at the moon",
    points: 0,
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "left", isRight: false },
      { id: 1, text: "right", isRight: false },
      { id: 2, text: "wrong", isRight: true },
    ],
  },
  {
    id: 6,
    title: "Question 7: What is right?",
    comment: "Right answer is at the moon",
    points: 0,
    maxPoints: 1,
    type: 0,
    shuffleOptions: true,
    aiCheck: true,
    plagiarismCheck: true,
    allowFiles: false,
    files: [],
    previews: [],
    selected: false,
    answerOptions: [
      { id: 0, text: "left", isRight: false},
      { id: 1, text: "right", isRight: false },
      { id: 2, text: "wrong", isRight: true },
    ],
  },]